spring:
  datasource:
    diver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://largedb.csjvf23ojub6.ap-northeast-2.rds.amazonaws.com:3306/largeDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: s.j3033212

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

jwt:
  secret: 2314567890789654367897087689578467356425376847950865794638497

  access:
    expiration: 3600
    header: Authorization

  refresh:
    expiration: 1209600
    header: Authorization-refresh

server:
  error:
    include-exception: true
    include-message: always

cloud:
  aws:
    s3:
      bucket: large-devlog-image
      folder:

    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA6OQWFGSUHKNFTSFK
      secret-key: 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
      instance-profile: true
