spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:large
    username: sa
    password:
    driver-class-name: org.h2.Driver


jwt:
  secret: 2314567890789654367897087689578467356425376847950865794638497

  access:
    expiration: 3600
    header: Authorization

  refresh:
    expiration: 1209600
    header: Authorization-refresh

server:
  error:
    include-exception: true
    include-message: always